### ISSUE TITLE
Save hOCR dialog on Linux does not list existing .HTML files

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#210]
The save dialog on Linux does not list existing .HTML files in the current folder, while the open dialog does. Also working fine on Windows.
OS: Debian Buster 9 (testing)
gIR: 3.2.3

**Comment by manisandro** [comment]
Are you using the gtk or qt interface?

**Comment by SantosSi** [comment]
The file installed by the Debian package is gimagereader-gtk.

**Comment by manisandro** [comment]
Seems to affect only the kdialog base file open/save dialogs. Should be fixed in 
4f79ba0.

**Comment by SantosSi** [comment]
This is still unresolved: .html files are still not listed. Found something that could be the cause: there could be an extra blank space in the suffix. In the GTK open file requester it reads: 
`hOCR HTML Files(*.html )` please note the space after html and before the closing parenthesis.

**Comment by manisandro** [comment]
Hm, unable to reproduce, but there was indeed an extra whitespace in FileFilter::to_kde_filter (but this should not affect the GTK dialog). Please try again with latest master, otherwise could you post a screenshot of the dialog which is misbehaving?

**Comment by SantosSi** [comment]
You are right: the extra whitespace was not the reason, because the problem persists. Screenshot:
![screenshot_20171229_133154](https://user-images.githubusercontent.com/31543615/34437282-344c703c-ec9d-11e7-9ec3-c91dfacea1a8.png)

**Comment by manisandro** [comment]
That's the KDE dialog though. What version of kdialog do you have?

**Comment by SantosSi** [comment]
$ kdialog -v
Qt: 4.8.7
KDE: 4.14.36
KDialog: 1.0

**Comment by manisandro** [comment]
Uh ok, that's a pretty old one. The command I use to open is

    /usr/bin/kdialog --getopenfilename <initialDir> "hHOCR HTML Files (*.html)"

if you run this command separately, can you reproduce the problem (actually I see there is a space missing between "Files" and "(*.html)", perhaps that has an effect. Can you experiment a bit and find out which command works correctly?

**Comment by SantosSi** [comment]
It works with:
`/usr/bin/kdialog --getopenfilename /home/silveriots/Handlungsfeld_Ausbildung/ "*.html"` and
`/usr/bin/kdialog --getopenfilename /home/silverio/Documents/Handlungsfeld_Ausbildung/ "hOCR HTML Files *.html"`
so removing parethensis does the trick.

**Comment by manisandro** [comment]
Odd, that's not what [1] says. and kdialog from KF5 requires the parenthesis. I'm inclined to say this is a bug in this old version of kdialog.

[1] https://techbase.kde.org/Development/Tutorials/Shell_Scripting_with_KDE_Dialogs#Example_32._--getopenfilename_dialog_box_with_wildcard_filter

**Comment by SantosSi** [comment]
Confirming: Debian Testing Buster just updated the 
kdialog package to version 17.08.3-2, reporting:
$ kdialog -v                                                                 

Will you care for older versions with a compatibility 
switch or so?

**Comment by manisandro** [comment]
I could add an option to disable the use of kdialog in the gtk variant and force the usage of the gtk file open dialogs.
