### ISSUE TITLE
hOCR: Collapse/expand all nodes, including pages

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#246]
In the gtk version all page nodes can be expanded/collapsed by right-clicking the document node. In the Qt5 version there is no item to expand/collapse all nodes, neither a document node nor buttons exist to do so.

**Comment by manisandro** [comment]
The context menu entries for the various nodes are definitely still there. There is no root document node anymore since I reworked the code, true, but is there really a purpose of having such a root node?

**Comment by SantosSi** [comment]
The issue is about collapsing or expanding all of a PDF document's node at once. Currently it is only possible to do that per page in the Qt5 version.

**Comment by manisandro** [comment]
Addressed in the navigation toolbar, see #228

**Comment by SantosSi** [comment]
I find the toolbar a very good idea.
## Bugs:
- The expand all and collapse all buttons have effect only on the first page, no matter what node type is selected and what page is highlighted. I expected to have all pages expanded.
- Subordinate node types are expanded without opening the superordinate path. E.g. Expanding all paragraphs does not also expand the page and the text blocks they are in.

## Wishes:
Expanding all node types of a page is fine. But I would like to have that also globally, e.g. all words on all pages are expanded. Together with openening all superordinate nodes that would expand everything on all pages, as originally requested. This is especially useful for full text reviews, needed for finding false negatives (misspelled word, but not marked as such because it seems OK).

## UI:
Can you find icons better depicting the expand and collapse actions? The plus sign is percieved as an action to add something and the forbidden sign is usually understood for deactivating or deleting.

**Comment by manisandro** [comment]
Uh there was a general bug in the `HOCRDocument::nextIndex` function, so all the issues where only the first page was affected should now be fixed in current master. Perhaps this also fixes the search/replace issues you are having?

**Comment by manisandro** [comment]
I've now also put some more thought into the expand/collapse logic, I think it should address your points above. Also, I made a new attempt with the icons.

**Comment by SantosSi** [comment]
Great: expanding OK, affecting all pages and expanding superordinate nodes. Substitutions also OK.
Only a little issue appeared: when exanding all, the currently highlighted node is scrolled away.

**Comment by manisandro** [comment]
Should now be fixed.

Just for clarity: so the replaceAll/substitutions issues are also solved now?

**Comment by SantosSi** [comment]
Scrolling fix confirmed.
ReplaceAll (#225): also fixed.

**Comment by manisandro** [comment]
Cool (so the problem with replace was that I was always looking at the first page trying to reproduce the error, and I suppose you were working on a subsequent page).
So now I think the only remaining issue is that with your GTK build scroll-to-highlighted region does not work. Is that still so?

**Comment by SantosSi** [comment]
I am sorry, I lost track of the bug reports and improvements I reported, so I cannot give you a complete overview.
But yes, with GTK that specific issue still exists and I noticed the .html file requester issue is also there...

**Comment by manisandro** [comment]
Judging from which items I marked as "TODO" in my inbox, the gtk issue should be the only issue where we observe different behaviors of the program.

The html issue is an issue with the kdialog version you have installed not behaving as it is supposed to according to its own documentation. It is hard for me to fix because I don't know exactly which versions of kdialog it affects, in particular since there is no format that works with both the correctly behaving kdialog as well as the misbehaving one. Also, the KDE4 kdialog (which you are using) is actually obsolete and replaced by the KF5 variant, which behaves as documented.

**Comment by manisandro** [comment]
Also implemented for gtk

**Comment by SantosSi** [comment]
Tested OK for GTK.
If your TODOs are not for improvements but specifically for bugs, I also remember an issue with gIR not accepting bbox resizing after several changes to a document.
The file requester does work in the Qt version, but not in both GTK versions: the last release and the current master.

**Comment by SantosSi** [comment]
Found a recurring pattern in Qt: after adding 2 images resized bbox'es are not remembered.

**Comment by manisandro** [comment]
Indeed, fixed.
